version: "3.8"

services:
  sugarcane:
    image: "mucize-sugarcane"
    build:
      context: ./sugarcane
      dockerfile: Dockerfile.sugarcane
    ports:
      - "8000:8000"
    volumes:
      - ./sugarlib:/app/sugarlib    
      - ./sugarcane:/app/sugarcane 
      - ./content:/app/content
    command: ["python3", "sugarcane/app.py"]
    environment:
      - REDIS_HOST_CANE=redis
      - REDIS_PORT_CANE=6379
      - REDIS_DB_CANE=1
      - CANE_SERVER_LISTEN_HOST=0.0.0.0
      - CANE_SERVER_LISTEN_PORT=8000
      - R_PREFIX=CANE
      - MASTER_KEY=MASTER
      - EXPIRED_PREFIX=EXPIRED
      - EXPIRED_TTL=86400
    depends_on:
      - redis
  demo:
    build:
      context: ./demo_application  # Build the image from the demo_application directory
      dockerfile: Dockerfile.demo
    ports:
      - "5000:5000"
    volumes:
      - ./demo_application:/app/demo_application  # Mount the local demo directory to the container
      - ./sugarlib:/app/sugarlib    
    depends_on:
      - sugarcane  # Demo depends on sugarcane to be up before starting
      - redis
    environment:
      - REDIS_HOST_DEMO=redis
      - REDIS_PORT_DEMO=6379
      - REDIS_DB_DEMO=2
      - DEMO_APP_CANE_SERVER_HOST=http://sugarcane:8000
      - DEMO_APP_HOST=0.0.0.0
      - DEMO_APP_PORT=5000
      - DEMO_APP_R_PREFIX_NODE=CC:NODE
      - DEMO_APP_R_PREFIX_MASTER=CC:MASTER1
      - MASTER_TTL=10
      - NODES_TTL=100
    command: ["python3", "demo_application/app.py"]
  content:
    image: "mucize-sugarcane"
    volumes:
      - ./sugarlib:/app/sugarlib  # Mount the local demo directory to the container
      - ./content:/app/content
    command: ["python3", "content/faker.py", "loop"]
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST_CANE=redis
      - REDIS_PORT_CANE=6379
  redis:
    image: "redis:alpine"
    ports:
      - "63791:6379"
