version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}-db
    environment:
      - POSTGRES_DB=${CANE_DATABASE_NAME}
      - POSTGRES_USER=${CANE_DATABASE_USER}
      - POSTGRES_PASSWORD=${CANE_DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/:rw
    ports:
      - ${EXPOSED_DATABASE_PORT}:5432
    env_file:
      - .env

  sugarcanedj:
    image: mucize-sugardj
    container_name: ${PROJECT_NAME}-dj
    build:
      context: ./sugardj
      dockerfile: Dockerfile
    command: ["uwsgi", "--http", "0.0.0.0:8000", "--master", "-p", "4", "-w", "config.wsgi:application"]
    env_file:
      - .env
    volumes:
      - ./sugarlib:/app/sugarlib
      - ./sugardj:/app/sugardj
      - ./content:/app/content
      - .env:/app/.env
    ports:
      - ${EXPOSED_CANE_DJ_PORT}:8000
    depends_on:
      - redis
      - db
  
  sugarcane:
    image: mucize-sugarcane
    container_name: ${PROJECT_NAME}-server
    build:
      context: ./sugarcane
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_CANE_SERVER_PORT}:5000"
    volumes:
      - ./sugarlib:/app/sugarlib
      - ./sugarcane:/app/sugarcane
      - ./content:/app/content
      - .env:/app/.env
    command: ["uwsgi", "--http", "0.0.0.0:5000", "--master", "-p", "4", "-w", "sugarcane.app:app"]
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "${EXPOSED_REDIS_PORT}:6379"
    env_file:
      - .env

volumes:
  pgdata:
