version: "3.8"

services:
  sugarcane:
    restart: always
    command: "python3 sugarcane/main.py"
  jaggery:
    restart: always
    tty: true
    stdin_open: true
    command: "python3 jaggery/manage.py runserver 0.0.0.0:8000"
